name: CI/CD

on: 
  workflow_dispatch:
  
  push:
    paths:
      - 'Codes/Julia/**'
      - 'Docker/**'

jobs:
  
  clone:
    runs-on: ubuntu-latest
    steps:
        - name: clone repo
          uses: actions/checkout@v4
  
  authentication:
    runs-on: ubuntu-latest
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
              username: ${{ secrets.DOCKER_HUB_USERNAME }}
              password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

  jlai-p1:
    runs-on: ubuntu-latest
    needs: 
      - clone
      - authentication
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
            context: .
            file: ./Docker/Dockerfile-1
            # platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jlai-p1:latest

  jlai-p2:
    runs-on: ubuntu-latest
    needs: 
      - clone
      - authentication
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
            context: .
            file: ./Docker/Dockerfile-2
            # platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jlai-p2:latest

  jlai-p3:
    runs-on: ubuntu-latest
    needs: 
      - clone
      - authentication
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
            context: .
            file: ./Docker/Dockerfile-3
            # platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jlai-p3:latest
