name: CI/CD-P1

on:

  workflow_dispatch:

  push:
    paths:
      - 'Codes/Julia/**'
      - 'Docker/**'

jobs:
  
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Docker/Dockerfile-1
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jlai-p1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max



