name: JLAI

on: 
  push:
    paths:
      - 'Codes/Julia/**'
      - 'Docker/**'
  workflow_dispatch:

jobs:
  
  jlai-p1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: abmhamdi
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile-1
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: abmhamdi/jlai-p1:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  jlai-p2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: abmhamdi
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile-2
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: abmhamdi/jlai-p2:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  jlai-p3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: abmhamdi
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile-3
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: abmhamdi/jlai-p3:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
